Capturing Standardisation Learning
nhsengland/privfp-experiments pull request #34
Opened 2024-06-21 10:59 UTC by scarlett-k-nhs

# Summary

**What/Why**

This branch adds standardisation spike research to the mkdocs.

2024-07-15 14:58 UTC, willpoulett requested changes
Really good and interesting research! Only 3 small typo-like comments.

2024-07-15 14:58 UTC, willpoulett commented on docs/standardisation-research/index.md
> +2. **Entity type specific:** We likely want to handle specific entities in a certain way and have a generalised way to begin with)
Is an extra )

2024-07-15 14:58 UTC, willpoulett commented on docs/standardisation-research/standardising_with_knowledge_graphs.md
> +[KnowledgeGraph](https://github.com/rahulnyk/knowledge_graph): This demonstrates a framework from going from document to graph. - the codebase would likely need reworking.
. - should just be -

2024-07-15 14:58 UTC, willpoulett commented on docs/standardisation-research/standardising_with_knowledge_graphs.md
> +3. Then you can use this graph and created it over your documents.
sentence doesn't quite make sense

2024-07-30 13:11 UTC, danjscho approved these changes

2024-07-30 13:20 UTC, willpoulett approved these changes

2024-07-30 14:29 UTC, merged